'use client';
import { useEffect, useMemo, useState } from 'react';
import {supabase,inventoryData,inventoryCommand} from '../lib/supabase';
import { Package, ArrowDownLeft, ArrowUpRight, Download, Upload, Search, Plus, RefreshCw, History, Boxes, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import type { Product } from '@/lib/inventory-rules';
type Movement={id:string;product:string;sku:string;title:string;warehouse:string;type:string;quantity:number;before:number;after:number;reason:string;reference:string;actor:string;created:string;reversal?:string};
const labels:Record<string,string>={entrada:'Entrada',saida:'Saída','saida-reserva':'Saída de reserva',reserva:'Reserva',liberacao:'Liberar reserva',ajuste:'Contagem física',abertura:'Saldo inicial',estorno:'Estorno'};
const currency=(n:number|null)=>n===null?'Não informado':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:4}).format(n);
const number=(n:number)=>n.toLocaleString('pt-BR');
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
export default function Inventory({name}:{name:string}) {
 const [products,setProducts]=useState<Product[]>([]),[movements,setMovements]=useState<Movement[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [query,setQuery]=useState(''),[warehouse,setWarehouse]=useState('all'),[status,setStatus]=useState('all'),[page,setPage]=useState(0),[tab,setTab]=useState('stock');
 const [modal,setModal]=useState(''),[selected,setSelected]=useState<Product|null>(null),[draft,setDraft]=useState<Record<string,string>>({}),[operationId,setOperationId]=useState('');
 const [importRows,setImportRows]=useState<any[]>([]),[importFile,setImportFile]=useState(''),[importErrors,setImportErrors]=useState<string[]>([]),[historyQuery,setHistoryQuery]=useState(''),[historyType,setHistoryType]=useState('all'),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState('');
 const [exportWarehouse,setExportWarehouse]=useState(''),[exportScope,setExportScope]=useState('all');
 async function refresh(){setLoading(true);try {const data=await inventoryData();setProducts(data.products);setMovements(data.movements);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 useEffect(()=>{setPage(0)},[query,warehouse,status]);
 const warehouses=useMemo(()=>[...new Set(products.map(p=>p.warehouse))].sort(),[products]);
 const visible=products.filter(p=>(warehouse==='all'||p.warehouse===warehouse)&&`${p.sku} ${p.title} ${p.shelf}`.toLowerCase().includes(query.toLowerCase())&&(status==='all'||status==='zero'&&p.quantity===0||status==='low'&&p.minimum!==null&&p.quantity-p.reserved<=p.minimum||status==='reserved'&&p.reserved>0));
 const history=movements.filter(m=>`${m.sku} ${m.reason} ${m.actor} ${m.reference}`.toLowerCase().includes(historyQuery.toLowerCase())&&(historyType==='all'||historyType===m.type)&&(!dateFrom||m.created.slice(0,10)>=dateFrom)&&(!dateTo||m.created.slice(0,10)<=dateTo));
 const field=(key:string,value:string)=>setDraft(v=>({...v,[key]:value}));
 function open(kind:string,p?:Product){setSelected(p??null);setDraft({quantity:'',cost:'',reason:'',reference:'',sku:'',title:p?.title??'',minimum:p?.minimum?.toString()??'',warehouse:warehouses[0]??'My Warehouse',shelf:''});setOperationId(crypto.randomUUID());setError('');setNotice('');setModal(kind);}
 async function send(body:unknown){setBusy(true);setError('');try {const data=await inventoryCommand(body);setNotice(data.message);setModal('');setImportRows([]);await refresh();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();if(modal==='create')await send({action:'create',product:{...draft,quantity:draft.quantity||0,reserved:0,purchase:0,transit:0}});else if(modal==='edit')await send({action:'edit',productId:selected?.id,...draft});else await send({action:'move',productId:selected?.id,type:modal,id:operationId,...draft});}
 async function readExcel(file:File){setError('');setImportRows([]);setImportErrors([]);setImportFile(file.name);try {const XLSX=await import('xlsx');const book=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,nodim:true} as any);const rows=XLSX.utils.sheet_to_json<any[]>(book.Sheets[book.SheetNames[0]],{header:1,defval:null});const headers=rows[0]?.map(String)??[];const required=['SKU','Título','Armazém','Estoque Atual'];if(required.some(h=>!headers.includes(h)))throw new Error('Use a planilha Lista_de_Estoque com SKU, Título, Armazém e Estoque Atual. O modelo Update_warehouse é usado para exportação.');const index=(h:string)=>headers.indexOf(h);const issues:string[]=[];const seen=new Set<string>();const parsed=rows.slice(1).filter(r=>r.some(v=>v!==null&&v!=='')).map((r,i)=>{const get=(h:string)=>r[index(h)];const p={sku:String(get('SKU')??''),title:String(get('Título')??''),warehouse:String(get('Armazém')??'My Warehouse'),shelf:String(get('Estante')??''),minimum:get('Estoque Baixo'),quantity:get('Estoque Atual'),reserved:get('Ocupado')??0,purchase:get('Em Trânsito(Compra)')??0,transit:get('Em Trânsito(Transferência）')??0,cost:get('Custo Médio'),created:get('Criado') instanceof Date?(get('Criado') as Date).toISOString():String(get('Criado')??'')};const key=JSON.stringify([p.sku,p.warehouse,p.shelf]);if(seen.has(key))issues.push(`Linha ${i+2}: SKU duplicado no mesmo local.`);seen.add(key);if(!p.sku||!p.title)issues.push(`Linha ${i+2}: SKU ou título ausente.`);if(p.quantity===null||!Number.isSafeInteger(Number(p.quantity))||Number(p.quantity)<0||Number(p.reserved)>Number(p.quantity))issues.push(`Linha ${i+2}: saldo inválido.`);const available=get('Disponível');if(available!==null&&Number(available)!==Number(p.quantity)-Number(p.reserved))issues.push(`Linha ${i+2}: disponível diferente de estoque menos ocupado.`);return p;});if(parsed.length>2000)issues.push('Limite de 2.000 registros por importação.');setImportRows(parsed);setImportErrors(issues);setModal('import');}catch(e){setError((e as Error).message);}}
 async function exportExcel(){setBusy(true);setError('');try {if(!exportWarehouse)throw new Error('Selecione um armazém.');const rows=(exportScope==='filtered'?visible:products).filter(p=>p.warehouse===exportWarehouse);if(!rows.length)throw new Error('Nenhum produto para exportar.');const groups=new Map<string,Product[]>();rows.forEach(p=>groups.set(p.sku,[...(groups.get(p.sku)??[]),p]));const result:any[][]=[['SKU*','Estoque Baixo\n(Não será atualizado se não for preenchido)','Qtd. Total Atualizado\n(Não será atualizado se não for preenchido)','Custo Médio Atualizado\n(Não será atualizado se não for preenchido)']];for(const [sku,items] of groups){if(items.length>1&&new Set(items.map(p=>p.minimum)).size>1)throw new Error(`Revise o estoque mínimo de ${sku}: há limites diferentes entre estantes.`);const qty=items.reduce((s,p)=>s+p.quantity,0);let cost=items[0].cost;if(items.length>1){if(items.some(p=>p.quantity>0&&p.cost===null))cost=null;else if(qty)cost=items.reduce((s,p)=>s+p.quantity*(p.cost??0),0)/qty;else if(new Set(items.map(p=>p.cost)).size>1)throw new Error(`Revise o custo de ${sku}: não há saldo para ponderar custos diferentes.`);}result.push([sku,items[0].minimum,qty,cost]);}const XLSX=await import('xlsx');const book=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet(result);sheet['!cols']=[{wch:40},{wch:46},{wch:46},{wch:46}];sheet['!rows']=[{hpt:36}];XLSX.utils.book_append_sheet(book,sheet,'Sheet1');XLSX.writeFile(book,`Update_warehouse_SKU01_${new Date().toISOString().replace(/[-:T]/g,'').slice(0,14)}.xlsx`);setModal('');setNotice(`${result.length-1} SKUs exportados de ${exportWarehouse}.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function exportHistory(){const XLSX=await import('xlsx');const sheet=XLSX.utils.json_to_sheet(history.map(m=>({'Data':m.created,'SKU':m.sku,'Armazém':m.warehouse,'Tipo':labels[m.type]??m.type,'Quantidade':m.quantity,'Saldo anterior':m.before,'Saldo posterior':m.after,'Motivo':m.reason,'Referência':m.reference,'Responsável':m.actor})));const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Movimentações');XLSX.writeFile(book,'Historico_de_Estoque.xlsx');}
 const total=products.reduce((s,p)=>s+p.quantity,0),occupied=products.reduce((s,p)=>s+p.reserved,0),low=products.filter(p=>p.minimum!==null&&p.quantity-p.reserved<=p.minimum).length;
 return <div className="inventory-app"><header className="topbar"><div className="brand"><span className="brandmark"><Package size={24}/></span><div><b>ESTOQUE</b><small>Controle de produtos</small></div></div><div className="account"><span>{name}</span><button onClick={()=>void supabase.auth.signOut()}>Sair</button></div></header><main className="workspace"><div className="heading"><div><p className="eyebrow">SEU ESTOQUE, EM DIA</p><h1>Visão do estoque</h1><p className="muted">Registre movimentações e acompanhe cada produto.</p></div><div className="actions"><Button variant="outline" onClick={()=>{setExportWarehouse(warehouse==='all'?warehouses[0]??'':warehouse);setModal('export')}} disabled={!products.length}><Download size={17}/> Exportar Excel</Button><Button onClick={()=>open('create')}><Plus size={18}/> Novo produto</Button></div></div>
 <section className="metrics" aria-label="Resumo do estoque"><article><span>Produtos cadastrados</span><strong>{number(new Set(products.map(p=>p.sku)).size)}</strong><small>SKUs únicos</small></article><article><span>Unidades disponíveis</span><strong>{number(total-occupied)}</strong><small>{number(occupied)} reservadas · {number(total)} físicas</small></article><article className={low?'metric-alert':''}><span>No limite ou abaixo</span><strong>{number(low)}</strong><small>Produtos para reposição</small></article><article><span>Valor do estoque</span><strong className="money">{currency(products.reduce((s,p)=>s+p.quantity*(p.cost??0),0))}</strong><small>{products.some(p=>p.cost===null)?'Exclui produtos sem custo informado':'Com base no custo médio'}</small></article></section>
 {error&&<div className="message error" role="alert">{error}</div>}{notice&&<div className="message success" role="status">{notice}</div>}
 <Tabs value={tab} onValueChange={setTab}><div className="sectionbar"><TabsList><TabsTrigger value="stock"><Boxes size={16}/> Produtos</TabsTrigger><TabsTrigger value="history"><History size={16}/> Movimentações</TabsTrigger></TabsList><div className="actions"><label className="upload-control"><Upload size={16}/> Importar Excel<input type="file" accept=".xlsx" onChange={e=>{const file=e.target.files?.[0];if(file)void readExcel(file);e.target.value='';}}/></label><Button variant="ghost" size="icon" aria-label="Atualizar estoque" onClick={refresh} disabled={loading}><RefreshCw size={17} className={loading?'spin':''}/></Button></div></div>
 <TabsContent value="stock"><section className="panel"><div className="filters"><div className="search"><Search size={18}/><Input aria-label="Buscar produto" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por SKU, produto ou estante..."/></div><Choice label="Armazém" value={warehouse} onChange={setWarehouse} options={[["all","Todos os armazéns"],...warehouses.map(w=>[w,w] as [string,string])]}/><Choice label="Situação do estoque" value={status} onChange={setStatus} options={[["all","Todas as situações"],["zero","Sem estoque"],["low","No limite ou abaixo"],["reserved","Com reservas"]]}/></div>
 {loading&&!products.length?<div className="empty">Carregando estoque…</div>:!products.length?<div className="empty"><Package size={44}/><h2>Comece com a sua planilha</h2><p>Importe a lista de estoque para cadastrar os produtos e os saldos iniciais.</p><p className="muted">Use “Importar Excel” para escolher sua planilha.</p></div>:<><Table><TableHeader><TableRow><TableHead>Produto / SKU</TableHead><TableHead>Localização</TableHead><TableHead className="num">Atual</TableHead><TableHead className="num">Reservado</TableHead><TableHead className="num">Disponível</TableHead><TableHead className="num">Custo médio</TableHead><TableHead>Situação</TableHead><TableHead className="num">Movimentar</TableHead></TableRow></TableHeader><TableBody>{visible.slice(page*20,page*20+20).map(p=><TableRow key={p.id}><TableCell><button className="product-link" onClick={()=>open('detail',p)}>{p.title}</button><small className="sku">{p.sku}</small></TableCell><TableCell>{p.warehouse}<small className="sku">Estante {p.shelf||'não definida'}</small></TableCell><TableCell className="num">{number(p.quantity)}</TableCell><TableCell className="num muted">{number(p.reserved)}</TableCell><TableCell className="num available">{number(p.quantity-p.reserved)}</TableCell><TableCell className="num">{currency(p.cost)}</TableCell><TableCell><span className={`badge ${p.quantity===0?'zero':p.minimum!==null&&p.quantity-p.reserved<=p.minimum?'low':'ok'}`}>{p.quantity===0?'Sem estoque':p.minimum!==null&&p.quantity-p.reserved<=p.minimum?'Repor':'Em estoque'}</span></TableCell><TableCell><div className="row-actions"><Button variant="outline" size="sm" aria-label={`Registrar entrada de ${p.sku}`} onClick={()=>open('entrada',p)}><ArrowDownLeft size={16}/> Entrada</Button><Button variant="outline" size="sm" aria-label={`Registrar saída de ${p.sku}`} onClick={()=>open('saida',p)}><ArrowUpRight size={16}/> Saída</Button></div></TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<div className="empty">Nenhum produto encontrado com esses filtros.</div>}<div className="table-footer"><span>{number(visible.length)} registros · página {page+1} de {Math.max(1,Math.ceil(visible.length/20))}</span><div className="actions"><Button size="sm" variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</Button><Button size="sm" variant="outline" disabled={(page+1)*20>=visible.length} onClick={()=>setPage(p=>p+1)}>Próxima</Button></div></div></> }</section></TabsContent>
 <TabsContent value="history"><section className="panel"><div className="filters history-filters"><Input placeholder="Buscar SKU, motivo ou responsável" aria-label="Buscar movimentação" value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)}/><Choice label="Tipo de movimentação" value={historyType} onChange={setHistoryType} options={[["all","Todos os tipos"],...Object.entries(labels)]}/><label>De<Input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label>Até<Input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><Button variant="outline" onClick={exportHistory} disabled={!history.length}><Download size={16}/> Excel</Button></div><Table><TableHeader><TableRow><TableHead>Data / responsável</TableHead><TableHead>Produto</TableHead><TableHead>Movimentação</TableHead><TableHead className="num">Quantidade</TableHead><TableHead className="num">Saldo anterior → posterior</TableHead><TableHead>Motivo / referência</TableHead></TableRow></TableHeader><TableBody>{history.map(m=><TableRow key={m.id}><TableCell>{new Date(m.created).toLocaleString('pt-BR')}<small className="sku">{m.actor}</small></TableCell><TableCell>{m.sku}<small className="sku">{m.warehouse}</small></TableCell><TableCell><span className="badge">{labels[m.type]??m.type}</span></TableCell><TableCell className="num">{m.quantity}</TableCell><TableCell className="num">{m.before} → <b>{m.after}</b></TableCell><TableCell>{m.reason}<small className="sku">{m.reference}</small></TableCell></TableRow>)}</TableBody></Table>{!history.length&&<div className="empty">Nenhuma movimentação encontrada.</div>}<div className="table-footer">Exibindo {history.length} das últimas 2.000 movimentações.</div></section></TabsContent></Tabs>
 <footer className="footer">Controle de Estoque <span>Acesso privado · Valores em reais</span></footer></main>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy){setModal('');setError('')}}}><DialogContent className="stock-dialog"><DialogTitle>{modal==='export'?'Exportar atualização de estoque':modal==='import'?'Conferir importação':modal==='detail'?'Detalhes do produto':modal==='create'?'Cadastrar produto':modal==='edit'?'Editar cadastro':`${labels[modal]??'Movimentação'} de produto`}</DialogTitle><DialogDescription>{selected?selected.sku:modal==='export'?'Arquivo no formato Update_warehouse_SKU01.xlsx.':modal==='import'?importFile:'Preencha os dados abaixo.'}</DialogDescription>{error&&<div className="message error" role="alert">{error}</div>}
 {modal==='export'?<div className="form-stack"><label>Armazém<Choice label="Armazém para exportação" value={exportWarehouse} onChange={setExportWarehouse} options={warehouses.map(w=>[w,w])}/></label><label>Produtos<Choice label="Abrangência da exportação" value={exportScope} onChange={setExportScope} options={[["all","Todos do armazém"],["filtered","Apenas os filtrados na tela"]]}/></label><div className="info-box">4 colunas: SKU, estoque baixo, quantidade total atualizada e custo médio atualizado. Reservas e mercadorias em trânsito não alteram a quantidade física exportada.</div><Button onClick={exportExcel} disabled={busy}><Download size={17}/> {busy?'Gerando…':'Baixar arquivo Excel'}</Button></div>
 :modal==='import'?<div className="form-stack"><p><b>{importRows.length} registros</b> encontrados. Produtos já existentes no mesmo local serão mantidos, sem somar novamente os saldos.</p>{importErrors.length>0?<div className="message error">{importErrors.slice(0,8).map((e,i)=><p key={i}>{e}</p>)}</div>:<div className="info-box">Os novos registros serão lançados como saldo inicial e aparecerão no histórico.</div>}<div className="preview-list">{importRows.slice(0,6).map((r,i)=><p key={i}><span>{r.sku}</span><b>{r.quantity} un.</b></p>)}</div><Button disabled={busy||!!importErrors.length||!importRows.length} onClick={()=>send({action:'import',rows:importRows})}>{busy?'Importando…':'Confirmar importação'}</Button></div>
 :modal==='detail'&&selected?<div className="form-stack"><h3>{selected.title}</h3><div className="detail-grid"><div>Físico<strong>{selected.quantity}</strong></div><div>Reservado<strong>{selected.reserved}</strong></div><div>Disponível<strong>{selected.quantity-selected.reserved}</strong></div></div><p>Armazém: {selected.warehouse}<br/>Estante: {selected.shelf||'Não definida'}<br/>Estoque mínimo: {selected.minimum??'Não informado'}<br/>Custo médio: {currency(selected.cost)}<br/>Em trânsito (compra): {selected.purchase}<br/>Em trânsito (transferência): {selected.transit}<br/>Cadastro original: {selected.created}</p><div className="detail-actions">{['entrada','saida','reserva','liberacao','saida-reserva','ajuste','edit'].map(k=><Button key={k} variant="outline" onClick={()=>open(k,selected)}>{labels[k]??'Editar cadastro'}</Button>)}</div><Button variant="ghost" onClick={()=>{setHistoryQuery(selected.sku);setTab('history');setModal('')}}>Ver histórico deste produto</Button></div>
 :<form onSubmit={submit} className="form-stack">{modal==='create'?<><label>SKU<Input required value={draft.sku} onChange={e=>field('sku',e.target.value)}/></label><label>Nome do produto<Input required value={draft.title} onChange={e=>field('title',e.target.value)}/></label><div className="form-grid"><label>Armazém<Input required value={draft.warehouse} onChange={e=>field('warehouse',e.target.value)}/></label><label>Estante<Input value={draft.shelf} onChange={e=>field('shelf',e.target.value)}/></label></div></>:modal==='edit'?<label>Nome do produto<Input required value={draft.title} onChange={e=>field('title',e.target.value)}/></label>:<div className="info-box">Disponível: <b>{selected?selected.quantity-selected.reserved:0}</b> · Físico: {selected?.quantity} · Reservado: {selected?.reserved}</div>}
 {modal!=='edit'&&<label>{modal==='ajuste'?'Quantidade física contada':modal==='create'?'Saldo inicial':'Quantidade'}<Input type="number" required min={modal==='ajuste'||modal==='create'?0:1} step="1" value={draft.quantity} onChange={e=>field('quantity',e.target.value)}/></label>}
 {(modal==='entrada'||modal==='create')&&<label>{modal==='create'?'Custo médio inicial':'Custo unitário da entrada (opcional)'}<Input type="number" min="0" step="any" value={draft.cost} onChange={e=>field('cost',e.target.value)}/></label>}
 {(modal==='create'||modal==='edit')?<label>Estoque mínimo<Input type="number" min="0" step="1" value={draft.minimum} onChange={e=>field('minimum',e.target.value)}/></label>:<><label>Motivo / observações<Input required placeholder="Ex.: compra, venda, perda ou contagem" value={draft.reason} onChange={e=>field('reason',e.target.value)}/></label><label>Pedido ou documento (opcional)<Input value={draft.reference} onChange={e=>field('reference',e.target.value)}/></label></>}
 <Button type="submit" disabled={busy}>{busy?'Salvando…':modal==='create'?'Cadastrar produto':modal==='edit'?'Salvar cadastro':'Confirmar movimentação'}</Button></form>}
 </DialogContent></Dialog></div>;
}
